### ISSUE TITLE
Yosemite 10.10.4 (14E46) - Not Supported

### ISSUE THREAD

**Issue by Braceyourself** [w0lfschild/cDock#3]
Don't know where else to post this but I updated to Yosemite Beta Version 10.10.4 (14E26a) this morning and unfortunately cDock does't work on that version :(

**Comment by 676339784** [comment]
Yes, same issue here on the same version.

**Comment by w0lfschild** [comment]
Yup this is an issue with SIMBL.

https://github.com/norio-nomura/EasySIMBL/issues/25

**Comment by w0lfschild** [comment]
Please try this and report back

http://w0lfschild.github.io/pages/cdock_workaround.html

**Comment by cmotdibbler** [comment]
It worked and here is proof!

Had trouble at first but it seemed to work after I copied the bundles into root/Library/Application Support/SIMBL/Plugins/. 

Thanks and long live transparent dock!

**Comment by herbs** [comment]
Howdy,

The fix worked on both my 2011 21" iMac and 2012 11" MacBook Air running  OS X 10.10.4. Will there be an update so I can eliminate this fix?

I Exported the script as an application. Is there a better thing for me to do so the script runner doesn't flash on and off in the Dock?

Good Luck,
Herb Schulz

**Comment by w0lfschild** [comment]
Well lets see if this fixed in [8.0](https://github.com/w0lfschild/cDock/releases/tag/v8.0) 🙏

**Comment by herbs** [comment]
> On Jul 1, 2015, at 7:44 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Well lets see if this fixed in 8.0 🙏
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Howdy,

When I try to start this one up I get the following:




Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by w0lfschild** [comment]
@herbs You didn't post anything.

**Comment by Declannn** [comment]
hey, i updated to 10.10.4 just now and my cDock isn't working i have installed version 8 of cDock and still no change i want transparent dock back asap !

**Comment by w0lfschild** [comment]
@Declannn 

Did you try applying 
Were you asked for your password?

**Comment by Declannn** [comment]
yes tried the lot still nothing its gone to standard dock with a black bar behind the dock

**Comment by herbs** [comment]
Howdy,

Sigh, I guess that image got stripped!? Basically it is a window that says `Element ``settingb'': when using absolute positioning. you have to supply ``x'' and ``y'' attributes.' with an OK acceptance.

Should I remove something before running cDock 8.0?

Good Luck,
Herb Schulz

**Comment by Declannn** [comment]
THANKS I USED THE WORK AROUND AND ITS WORKED SWEEEEET CHEERS !!!

**Comment by herbs** [comment]
Howdy,

Some more information. I can't run cDock because of the error above. When I re-boot I got an error because `cDock Agent.app' isn't signed; I removed it from the login list. If I also remove my script/app from the login list I get the standard Dock. Adding the script back into the login list and it seems to work but, since I never got to run cDock.app this may be left over from before.

Good Luck,
Herb Schulz

**Comment by Declannn** [comment]
wouldn't be able to help you as its never happened to me sorry

**Comment by herbs** [comment]
Howdy,

Don't think it can happen to you since you're the owner of the software. But I still can't run cDock 8.0 since it can't open a window. See the message 4 messages above (two by me above).

Good Luck,

**Comment by Declannn** [comment]
im not the owner of cDock my friend ?

**Comment by herbs** [comment]
Howdy,

Declannn: sorry about that.

W0lfschild: as a final note: I noticed that the cDock_inject.app script/app is not executable on my system.

So I see three problems: 1)cDock won't run because of some problem mentioned above; 2)I can't get cDock Helper.app to run because it isn't signed; 3)the cDock_inject.app script/app is not executable on my system.

If I manually add my version of the script/app to the login list it works at startup.

Good Luck,
Herb Schulz

**Comment by w0lfschild** [comment]
@herbs 

I've figured out the error relating to

    Elementsettingb'': when using absolute positioning. you have to supply "x'' and "y'' attributes.'


To run an unsigned app right click > open > open

**Comment by herbs** [comment]
> On Jul 1, 2015, at 9:09 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> @herbs
> 
> I've figured out the error relating to
> 
> Elementsettingb'': when using absolute positioning. you have to supply "x'' and "y'' attributes.'
> 
> To run an unsigned app right click > open > open
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Howdy,

Hmmm... just tried that (Clt-Click and then Open for cDock.app) and got the same message.

Would removing the preference file help?

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by herbs** [comment]
Howdy,

In my message above I say `cDock Helper.app' but it should be `cDock Agent.app'. So the three problems I'm having are: 1)cDock won't run because of some problem mentioned above and using the usual Ctl-Click + Open operation for unsigned apps doesn't help; 2)I can't get cDock Agent.app to run at login because it isn't signed; 3)the cDock_inject.app script/app is not executable on my system (it's icon has that `circle with diagonal stroke' symbol).

Good Luck,
Herb Schulz

**Comment by w0lfschild** [comment]
Well lets see if this fixed in [8.1](https://github.com/w0lfschild/cDock/releases/tag/v8.1) 🙏

**Comment by herbs** [comment]
> On Jul 2, 2015, at 12:21 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Well lets see if this fixed in 8.1 🙏
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Howdy,

cDock.app now runs fine. When I first applied restart the Dock would restart but not with a transparent dock. I had to restart the `cDock Agent.app' (via the menubar icon) and then it worked. I also see that `cDock Agent.app' is now one of my Login Items.

However, when I log out and then log in get a dialog box with the message:

*********
"cDock Agent.app" can't be opened because it is from an unidentifed developer.

Your security preferences allow installation of only apps from the Mac App Store and identified developers.
*********

Note: this is with `cDock Agent.app' not `cDock.app'.

If I remove `cDock Agent.app' from my Login Items and add my version of the Apple Script application (the one given in the temporary fix) it all works fine on login.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by w0lfschild** [comment]
Like I already said...

To run an unsigned app right click > open > open

I'm not paying $100 a year so people can open my app easier.

**Comment by herbs** [comment]
Howdy,

Sigh... First, that app is embedded inside cDock.app->Contents->Resources->helpers. I hace no problem going there but most other will not dare to go there. Second, even if I go there and Ctl-Click (same as Right-Click) and choose Open I don't get to choose Open again as suggested in the comment. 

However, I did figure out how to allow `cDock Agent.app' to permanently open!!! After it failed to open I went to System Preferences->Security & Privacy and there was a comment there about `cDock Ageent.app' along with an `Open Anyway' button. Once I clicked on that button the comment disappeared. The next time I booted I got a comment that `cDock Agent.app' was downloaded from the internet (no mention of it not being signed) and once I said that was fine it's worked. So now all is working.

Good Luck,
Herb Schulz

**Comment by herbs** [comment]
Howdy,

After getting everything working on my iMac I just installed 8.1 on my MacBook Air. Before running cDock 8.1 for the first time I removed `cDock Agent.app' and temporary script from my Login Items. I then ran and applied the transparent dock and it all just worked. I now see that `cDock Agent.app' is again in my Login Items but logging out and then back in gave no problems!!! The security settings on both systems are the same so I don't know what was going on with my iMac.

Good Luck,
Herb Schulz

**Comment by progmistro** [comment]
Hey wolf and thanks for everything about cdock, I actually solved my problem that was with the SIMBL, so to fix this i went to ~/Library/ScriptingAdditions/SIMBL.osax and right clicked it and opened it I also went in the SIMBL by right clicking and going to Show Package Contents and went to every executable file and right clicked it and opened it, now that my problem is solved here is the message my console was giving me

2015-07-03 12:31:59.837 PM osascript[4177]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"

**Comment by jameskatt** [comment]
cDock 8.1 worked perfectly on my MacBook Air once I updated to 10.10.4
It did not work, however, with my MacBook Pro after the 10.10.4 update.  SIMBL is installed.
But Dock Themes don't work.  The other functions work.

I'll try the workarounds noted above...

**Comment by w0lfschild** [comment]
cDock already links /Library/Application Support/SIMBL/Plugins to ~/Library/Application Support/SIMBL/Plugins so I'm pretty sure that's not the issue especially if it worked on your Air and seems to be working for most people.
